# FROM sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.10_7_1.9.9_3.4.1
from debian:bookworm

RUN apt update
RUN apt install curl gnupg2 -y
RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian all main" | tee /etc/apt/sources.list.d/sbt.list
RUN echo "deb https://repo.scala-sbt.org/scalasbt/debian /" | tee /etc/apt/sources.list.d/sbt_old.list
RUN curl -sL "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x2EE0EA64E40A89B84B2DF73499E82A75642AC823" | apt-key add
RUN apt update
RUN apt install curl gcc g++ python3-dev build-essential git make gtkwave verilator openjdk-17-source sbt -y
RUN curl -L https://github.com/com-lihaoyi/mill/releases/download/0.11.7/0.11.7 -o /usr/local/bin/mill && chmod +x /usr/local/bin/mill
RUN curl -L https://github.com/lihaoyi/Ammonite/releases/download/2.5.11/2.13-2.5.11 -o /usr/local/bin/amm && chmod +x /usr/local/bin/amm
# RUN python3 -m pip install --no-cache-dir jupyterlab numpy scipy matplotlib pandas
